// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuJeHeltloTKcr51lSqEivyQer1NzCnxE',
    appId: '1:697432162412:android:cc3a74e04ec1e55ec69849',
    messagingSenderId: '697432162412',
    projectId: 'examduty-myversion',
    storageBucket: 'examduty-myversion.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsGJrpo6ZBpQdOB_5LuXVwMZj3aXn_kvg',
    appId: '1:697432162412:ios:6516a95c4da8700dc69849',
    messagingSenderId: '697432162412',
    projectId: 'examduty-myversion',
    storageBucket: 'examduty-myversion.firebasestorage.app',
    iosClientId: '697432162412-b7uii3dpnctf1q19fo7iu9kg1n4aj44i.apps.googleusercontent.com',
    iosBundleId: 'com.example.examDutyApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANsstanN1AFblIrLiVfZpKdV9WbzgMcyI',
    appId: '1:697432162412:web:1bd50e91e3197133c69849',
    messagingSenderId: '697432162412',
    projectId: 'examduty-myversion',
    authDomain: 'examduty-myversion.firebaseapp.com',
    storageBucket: 'examduty-myversion.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsGJrpo6ZBpQdOB_5LuXVwMZj3aXn_kvg',
    appId: '1:697432162412:ios:6516a95c4da8700dc69849',
    messagingSenderId: '697432162412',
    projectId: 'examduty-myversion',
    storageBucket: 'examduty-myversion.firebasestorage.app',
    iosClientId: '697432162412-b7uii3dpnctf1q19fo7iu9kg1n4aj44i.apps.googleusercontent.com',
    iosBundleId: 'com.example.examDutyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANsstanN1AFblIrLiVfZpKdV9WbzgMcyI',
    appId: '1:697432162412:web:c6f4b8cf3677186ec69849',
    messagingSenderId: '697432162412',
    projectId: 'examduty-myversion',
    authDomain: 'examduty-myversion.firebaseapp.com',
    storageBucket: 'examduty-myversion.firebasestorage.app',
  );

}